name: Deploy Porfolio on VPS

on:
    push:
        branches:
            - main
    workflow_dispatch: 

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: build application and dependencies
              uses: actions/setup-node@v4
              with:
                node-version: '18.18.0'
            - run: npm ci
            - run: npm run build

            - name: Upload dist folder as artifact
              uses: actions/upload-artifact@v4
              with:
                name: dist
                path: dist/
    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Download dist artifact
              uses: actions/download-artifact@v4
              with:
                name: dist
                path: dist
            - name: Display structure of downloaded files
              run: ls -R dist

            - name: Deploy to DigitalOcean
              run: |
                # Save the private SSH key to a file
                echo -e "${{ secrets.SSH_KEY }}" > /tmp/id_rsa
                chmod 600 /tmp/id_rsa
                
            - name: Copy the contents of the dist folder to the server
              uses: easingthemes/ssh-deploy@main
              with:
                SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
                ARGS: "-rlgoDzvc -- delete"
                SOURCE: "dist/"
                REMOTE_HOST: ${{ secrets.SSH_HOST }}
                REMOTE_USER: ${{ secrets.SSH_USERNAME }}
                # REMOTE_PORT: ${{vars. REMOTE_PORT}}
                TARGET: ${{ secrets.SSH_FOLDER }}
            #   env:
            #     DO_HOST: ${{ secrets.SSH_HOST }}  # The hostname or IP address of your server
            #     DO_USER: ${{ secrets.SSH_USERNAME }}  # The SSH user for your server (e.g., 'root' or 'username')
            #     DO_FOLDER: ${{ secrets.SSH_FOLDER }}  # The SSH user for your server (e.g., 'root' or 'username')
            #   run: |
            #     # Copy the contents of the dist folder to the server
            #     rsync -avz --delete -e "ssh -i /tmp/id_rsa -o IdentitiesOnly=yes -o StrictHostKeyChecking=no" dist/ $DO_USER@$DO_HOST:$DO_FOLDER  # Adjust path as necessary
                
            - name: Restart Web Server 
              env: 
                DO_HOST: ${{ secrets.SSH_HOST }}  # The hostname or IP address of your server
                DO_USER: ${{ secrets.SSH_USERNAME }}  # The SSH user for your server (e.g., 'root' or 'username')
                DO_RESTART_SERVER: ${{ secrets.SSS_RESTART_SERVER }}  # The SSH user for your server (e.g., 'root' or 'username')
              run: | 
                # restart webserver
                ssh -i /tmp/id_rsa $DO_USER@$DO_HOST "$DO_RESTART_SERVER"
            
            - name: Clean up
              run: |
                # Clean up
                rm /tmp/id_rsa

        
